env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

language: cpp

compiler:
  - clang
  - gcc

sudo: false

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install gettext;
      brew link gettext --force;
    fi
# Don't use real gcc on OS X, problems arise when
# Hunspell built with gcc is linked with cppunit built with clang.
# Homebrew builds are build with clang
before_script:
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export CXX="g++-5" CC="gcc-5";
    fi

script:
  - autoreconf -i && ./configure && make && make check
  - bundle exec rspec
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then autoreconf -i -I /usr/local/share/aclocal && ./configure && make && make check; fi
# might be needed for future

after_failure:
  - cat tests/hun2/test-suite.log
  - cat tests/v1cmdline/test-suite.log
  - cat tests/test-suite.log

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - autopoint
    - gcc-5
    - g++-5
    - libboost-locale-dev
    - libboost-system-dev

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
